### PR TITLE
remove stand alone server

### PR DESCRIPTION
**Pull request by ashleyhood**
This is the pull request for issue #7

### CODE REVIEW

**Comment by TheFox** [comment]
You removed a bit too much. The `Makefile` is needed.

**Comment by ashleyhood** [comment]
Sorry. I was a bit over aggressive ;)

Do you need release.sh as well?

**Comment by TheFox** [comment]
I'm thinking about a less radical way, like this: 6d94ef1791830e934a39da06128592d97fc8d4ee
I'll consider the other changes, but rather in separate steps. Maybe I'll also remove `release.sh` and the changes for `.travis.yml` and the tests on `composer.json` you made. `smtpd.sublime-project` is needed. I don't know if it's a good idea to completely getting rid of `bootstrap.php` and the `scripts` in `composer.json`.

**Comment by ashleyhood** [comment]
I am happy either way as your solution fixes my issue with composer conflicts.  If you want, I will just close this pull request.

**Comment by TheFox** [comment]
Ok, cool. :)

**Pull request closed without merging**
